'use strict';

export enum JSON_ERROR {

    EXPECT_CHARACTER = 1,
    EXPECT_ESCAPE_CHARACTER = 2,
    EXPECT_ESCAPE_UNICODE = 3,
    EXPECT_PROPERTY_KEY = 4,
    EXPECT_DIGIT = 5,
    EXPECT_NUMBER_IDENTIFIER = 6,
    EXPECT_INFINITY = 7,
    EXPECT_NAN = 8,
    EXPECT_EXPONENT_NUMBER = 9,
    EXPECT_BOOLEAN_TRUE = 10,
    EXPECT_BOOLEAN_FALSE = 11,
    EXPECT_NULL = 12

} 